### ISSUE TITLE
sbt instruction in readme doesn't work

### ISSUE THREAD

**Issue by Daenyth** [clovellytech/outwatch-examples#10]
It's possible I'm doing something wrong or am missing some kind of required setup - I haven't done things with scala.js before.

```
sbt:outwatch-examples> outwatch-examples-directory/dev
[error] Expected ':'
[error] Not a valid key: dev (similar: deliver, doc, update)
[error] outwatch-examples-directory/dev
[error]                                ^
sbt:outwatch-examples> dev
[info] Updating ...
[info] Done updating.
[success] Total time: 1 s, completed May 30, 2019 4:29:37 PM
[error] No such setting/task
[error] fastOptJS::startWebpackDevServer
[error]
```

On osx after a fresh git clone and `sbt update`

**Comment by zakpatterson** [comment]
Hey @Daenyth  thanks for reporting, and thanks for trying out this project. I agree, it seems I misunderstood how command aliases work.

In `build.sbt` the alias is being added to several projects as:
```
    addCommandAlias("dev", "; compile; fastOptJS::startWebpackDevServer; devwatch; fastOptJS::stopWebpackDevServer"),
```
But I think the alias just doesn't work if you do `project_name/command_name`

So can you try (in sbt) 
```
> project outwatch-examples-directory   // switch current project
> dev         // call command alias
```
And feel free to open a PR to update this, or I can do it later too.

Thanks again!

**Comment by Daenyth** [comment]
That got me farther, now I get this:
```
[info] Compiling 2 Scala sources to /Users/gavin/code/outwatch-examples/examples/target/scala-2.12/classes ...
[info] Done compiling.
[success] Total time: 33 s, completed Jun 3, 2019 10:25:56 AM
[info] Updating NPM dependencies
[info] Fast optimizing /Users/gavin/code/outwatch-examples/examples/target/scala-2.12/scalajs-bundler/main/outwatch-examples-directory-fastopt.js
[error] yarn install v1.15.2
[error] info No lockfile found.
[error] [1/4] Resolving packages...
[error] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[error] error Couldn't find match for "bac3e6a" in "refs/heads/check-parent-exists,refs/heads/check-parent-exists-dist,refs/heads/equalityfn-thunk,refs/heads/fix-elm-child,refs/heads/gh-pages,refs/heads/master,refs/heads/modular,refs/heads/multiple-event-handlers,refs/heads/new-thunk,refs/heads/next,refs/heads/next-optimize,refs/heads/patch-under-container,refs/heads/replace-root,refs/heads/set-boolean-attributes-correctly,refs/heads/type-tweaks,refs/tags/0.7.3,refs/tags/v0.2.2,refs/tags/v0.2.3,refs/tags/v0.2.7,refs/tags/v0.2.8,refs/tags/v0.3.0,refs/tags/v0.3.1,refs/tags/v0.3.2,refs/tags/v0.3.3,refs/tags/v0.3.4,refs/tags/v0.4.0,refs/tags/v0.4.1,refs/tags/v0.4.2,refs/tags/v0.5.0,refs/tags/v0.5.1,refs/tags/v0.5.2,refs/tags/v0.5.3,refs/tags/v0.5.4,refs/tags/v0.6.0,refs/tags/v0.6.1,refs/tags/v0.6.2,refs/tags/v0.6.3,refs/tags/v0.6.4,refs/tags/v0.6.5,refs/tags/v0.6.6,refs/tags/v0.6.7,refs/tags/v0.6.8,refs/tags/v0.6.9,refs/tags/v0.7.0,refs/tags/v0.7.1,refs/tags/v0.7.2,refs/tags/v0.7.3" for "git://github.com/cornerman/snabbdom.git".
[error] java.lang.RuntimeException: Non-zero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at scalajsbundler.util.Commands$.$anonfun$run$9(Commands.scala:38)
[error] 	at scala.util.Either.fold(Either.scala:189)
[error] 	at scalajsbundler.util.Commands$.run(Commands.scala:38)
[error] 	at scalajsbundler.ExternalCommand.run(ExternalCommand.scala:22)
[error] 	at scalajsbundler.ExternalCommand$.$anonfun$install$1(ExternalCommand.scala:76)
[error] 	at scalajsbundler.ExternalCommand$.syncYarnLockfile(ExternalCommand.scala:46)
[error] 	at scalajsbundler.ExternalCommand$.install(ExternalCommand.scala:76)
[error] 	at scalajsbundler.sbtplugin.NpmUpdateTasks$.$anonfun$npmUpdate$1(NpmUpdateTasks.scala:36)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:293)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:288)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at scalajsbundler.sbtplugin.NpmUpdateTasks$.npmUpdate(NpmUpdateTasks.scala:46)
[error] 	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$.$anonfun$perConfigSettings$5(ScalaJSBundlerPlugin.scala:573)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / npmUpdate) Non-zero exit code: 1
[error] Total time: 6 s, completed Jun 3, 2019 10:26:02 AM
sbt:outwatch-examples-directory>
```

**Comment by zakpatterson** [comment]
@Daenyth I'm still working on this, and mostly trying to get travis to cooperate.

**Comment by Daenyth** [comment]
It runs now!

When I visit localhost:8080, I get a blank page and the request for `/outwatch-examples/directory/outwatch-examples-directory-opt-bundle.js` returns 404.

**Comment by zakpatterson** [comment]
try localhost:8080/index-dev.html. I had a hard time getting webpack's config to use index-dev by default for development. (that's in the readme now!)

**Comment by zakpatterson** [comment]
Btw I'd love your input on #16, it would be nice to continue expanding this.

**Comment by Daenyth** [comment]
That did it!
